### ISSUE TITLE
Add utils for Bybit backtesting

### ISSUE THREAD

**Issue by DeevsDeevs** [nautechsystems/nautilus_trader#2125]
**Background**  
---
Currently, Binance has stopped publishing quote and trade tick data, which has made it less useful for backtesting. Fortunately, Bybit provides high-quality, free market data, including daily published order book L2 data with a depth of 500.  

In Nautilus Trader, there is a `BinanceOrderBookDeltaDataLoader` that works specifically with Binance data. A similar loader for Bybit does not yet exist, but it would be a valuable addition to the project.  

Additionally, I noticed a comment in `nautilus_trader/nautilus_trader/persistence/loaders.py` about potentially moving `BinanceOrderBookDeltaDataLoader` into the Binance adapter:  
```python
# TODO: Eventually move this into the Binance adapter
```  
This raises the question of where such loaders should live—within specific adapters or in the more general `loaders.py`.  

---

**Proposal**
---
Add a `BybitOrderBookDeltaDataLoader` that:  
- Handles Bybit's daily L2 order book data (depth 500) for backtesting.  
- Works similarly to `BinanceOrderBookDeltaDataLoader`.  
---

**Implementation Tasks**
---

- [x] Add a new `BybitOrderBookDeltaDataLoader` implementation.  
- [x] Update documentation with examples and mini-tests for the Bybit loader.  
- [x] Address the `TODO` comment regarding the placement of loaders:  
      - Either move the Binance loader to the Binance adapter (and place the Bybit loader in its adapter), or  
      - Add the Bybit loader to `loaders.py`, keeping it consistent with the current structure.  

---

**Open Question**  
---
What is the best location for exchange-specific loaders:  
1. Move them into their respective adapters (e.g., Binance adapter, Bybit adapter)?  
2. Keep them in `loaders.py` for now?
---

I’d appreciate your thoughts on this before submitting a PR.

**Comment by cjdsellers** [comment]
Hi @DeevsDeevs

Thanks for proposing this, I agree it would be a valuable addition!

Your observation is correct, we're going with a pattern of including integration specific data loaders within the adapter subpackages (or crates). So this is similar to the approach for Databento and Tardis right now, where the specific data loaders are within their respective subpackages.

We'll continue to support more generic wrangling also, but the specific loaders do lower the friction when the data format is known and its now necessary to go through an intermediate dataframe.

I'll standardize the location of the `BinanceOrderBookDeltaDataLoader`.

Did you want me to assign this Bybit loader enhancement to yourself, and set to in progress?

**Comment by DeevsDeevs** [comment]
Hey @cjdsellers,

Yes, I already have some working code and am ready to create a PR for it.
I’ll wait for you to decide on the location of BinanceOrderBookDeltaDataLoader so I can follow the same approach for Bybit.

**Comment by cjdsellers** [comment]
Now closed from bef29a98adbc2dbde31b6726269782d02516345a.

Many thanks @DeevsDeevs.
