### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by OnlyC** [nautechsystems/nautilus_trader#405]
Hello,
I tried to install this and it went smooth, backtest is fast & code base is clean. I really like this project and that makes me want to dive right in to develop strategies & writing indicators. 
Just one more obstacle is lack of documents, especially USER GUIDE part. 

Thank you!

**Comment by cjdsellers** [comment]
Hi @OnlyC 

Thank you for taking the time to provide this feedback!

We've taken your comments on board and there has been some renewed efforts to start completing the documentation. We have a new hosting solution at GitBook https://docs.nautilustrader.io/

You will see in the coming days and weeks many more User Guides being added.

Please keep us updated on how you find these, and feel free to provide further feedback!

**Comment by cjdsellers** [comment]
There is so much documentation to write that this issue is likely to keep getting rolled from release to release. Moving this back to the roadmap and will break this up into more granular sub-tasks which I'll keep a running list of here.

- [ ] Getting started: Core concepts
- [ ] User Guide: Writing indicators
- [ ] User Guide: Writing strategies
- [ ] User Guide: Backtesting

TBC...

**Comment by cjdsellers** [comment]
Docs are currently an ongoing effort, closing this in favor of more specific requests / issues. Many thanks! :pray:
