### ISSUE TITLE
Binance integration

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#429]
Given the recent announcement on discontinuing CCXT support #428 opening this issue to track general discussions on a prioritized Binance integration.

- [ ] Add margin functionality to SPOT API adapters.
- [x] Add HTTP API adapter for data SPOT.
- [x] Add HTTP API adapter for execution SPOT.
- [x] Add HTTP API adapter for data USD-M-Futures.
- [x] Add HTTP API adapter for execution USD-M-Futures.
- [x] Add HTTP API adapter for data COIN-M-Futures.
- [x] Add HTTP API adapter for execution COIN-M-Futures.
- [x] Add WebSocket adapter for data SPOT.
- [x] Add WebSocket adapter for execution SPOT.
- [x] Add WebSocket adapter for data USD-M-Futures.
- [x] Add WebSocket adapter for execution USD-M-Futures.
- [x] Add WebSocket adapter for data COIN-M-Futures.
- [x] Add WebSocket adapter for execution COIN-M-Futures.
- [x] `DataClient` implementation handling USD-M-Futures and COIN-M-Futures.
- [x] `ExecutionClient` implementation handling USD-M-Futures and COIN-M-Futures.

**Comment by cjdsellers** [comment]
The adapter client example templates have been updated bfd3d454e4091c25238558ec24b18e0fe1ff4978.

**Comment by cjdsellers** [comment]
There has been some progress on the Binance integration. Currently it is ready for early pioneer beta testing for SPOT market trading from the `develop` branch. You can find some examples [here](https://github.com/nautechsystems/nautilus_trader/tree/develop/examples/live) .

Note you'll need to setup your `BINANCE_API_KEY` and `BINANCE_API_SECRET` env vars, or copy-paste those into the appropriate config fields.

**Limitations**
- Execution reconciliation has not yet been implemented. A complete overhaul of how reconciliation works in the platform is planned. So it is recommended to run this early version without a Redis persisted cache (as per the examples).
- External orders (say submitted from a web or mobile client) are not yet properly handled so all orders should originate from NautilusTrader. Again, a complete overhaul of how this works in the platform is planned.
- Multi/sub account, margin and futures trading not yet implemented.

**Data**
The `BinanceDataClient` has all functionality implemented including the order book and custom data types for the `BinanceTicker` and `BinanceBar` (which contains additional data beyond the regular `Bar` dtype.

**Execution**
The `BinanceExecutionClient` can handle `MARKET`, `LIMIT` and `STOP_LIMIT` order types, with all TIF and execution options available including `post_only` and icebergs (`display_qty`).

**Roadmap**
The current plan is to soon move to looking at the FTX integration, prior to implementing Binance sub-accounts, OCO orders, and margin or futures trading.

**Comment by cjdsellers** [comment]
As per #500 we need to add some functionality to this integration.

- [ ] Add margin functionality to SPOT API adapters.
- [ ] Add HTTP API adapter for data USD-M-Futures.
- [ ] Add HTTP API adapter for execution USD-M-Futures.
- [ ] Add HTTP API adapter for data COIN-M-Futures.
- [ ] Add HTTP API adapter for execution COIN-M-Futures.
- [ ] Add WebSocket adapter for data USD-M-Futures.
- [ ] Add WebSocket adapter for execution USD-M-Futures.
- [ ] Add WebSocket adapter for data COIN-M-Futures.
- [ ] Add WebSocket adapter for execution COIN-M-Futures.

**Comment by MikeCoderr** [comment]
Hi,
I would be really interested in the USD-M-Futures.
What is your realistic timeline?
If I would be willing to pay for that, what would the cost be to get it implemented sooner?

Do you think it makes sense to integrate this: https://github.com/ccxt/ccxt if possible with the event based approach?
So, that way, the connectors are all there and then later on, if the projects gets more traction, since people using it live - since many crypto exchanges are connected, then rebuild certain connectors by yourself?

Thanks
Mike

**Comment by cjdsellers** [comment]
Hi Mike,

Thanks for your interest in the project!

Indeed a full integration for Binance USD-M-Futures is not a trivial undertaking. Due to finite resources we welcome external sponsorship to help grow the capabilities of the project for everyone.

You're welcome to email us directly at info@nautechsystems.io where we can discuss further details.

**Comment by cjdsellers** [comment]
This integration has been maturing and stabilizing, now being tested by several users. An open task remaining is implementing more of the Margin account functionality (Spot and Futures are much further ahead right now).

Closing this in favor of specific issues.
