### ISSUE TITLE
FTX Integration

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#517]
Work is underway on the FTX crypto exchange integration.

- [x] HTTP REST API adapter
- [x] WebSocket API adapter public channels
- [x] WebSocket API adapter private channels
- [x] `FTXInstrumentProvider`
- [x] `FTXDataClient`
- [x] `FTXExecutionClient`
- [x] Reconciliation operations
- [ ] Reconciliation for trigger orders
- [ ] Account margin calculations
- [x] Trigger order handling
- [ ] `msgpsec` schemas
- [ ] Tests

**Comment by cjdsellers** [comment]
The FTX integration is now complete to a basic level and ready for careful beta testing by users.

All data seems to be working, and I've tested execution with both `MARKET` and `LIMIT` order types, as per the following examples:
https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/live/ftx_example.py
https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/live/ftx_example_market_maker.py

As per the examples, I suggest you run without a Redis cache because if order reconciliation is necessary on startup, this will currently fail.

The next step is to check the implementation of some of the advanced order types and execution options, and implement the reconciliation operations. 

I'll leave this issue open for a little while longer to answer any questions or for feedback on anyones testing experiences!

**Comment by cjdsellers** [comment]
We've added a hook to enable FTX US (set the `us` config option to `True`).

See the following example:
```
    exec_clients={
        "FTX": {
            # "api_key": "YOUR_FTX_API_KEY",
            # "api_secret": "YOUR_FTX_API_SECRET",
            # "subaccount": "YOUR_FTX_SUBACCOUNT", (optional)
            "us": False,  # If client is for FTX US
        },
    },
```
https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/live/ftx_example.py
https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/live/ftx_example_market_maker.py

**This is currently untested - if someone is able to report back if it works that would be much appreciated!**

**Comment by cjdsellers** [comment]
For anyone who has been testing the FTX adapter, the execution WebSocket is now operating properly and reliably (it was being disconnected after 3 minutes due lack of a correct ping strategy).

The reconciliation is also much more solid now, reconnects also result in a full mass status reconciliation which has been picking up lost messages/status occurring just after disconnects when under test.

Manually canceling open orders through the web GUI is being handled correctly.

Improvements pushed to latest `develop` branch.

**Comment by cjdsellers** [comment]
The following order types can now be submitted, modified, updated (trailing stops) and canceled on FTX:
- `STOP_MARKET` 
- `STOP_LIMIT`
- `MARKET_IF_TOUCHED`
- `LIMIT_IF_TOUCHED`
- `TRAILING_STOP_MARKET`
(the `TRAILING_STOP_LIMIT` order type is not supported on FTX)

The following caveats apply:
- Reconciliation _involving trigger orders_ will not work (this is because of the current FTX API design which does not link triggers with the original `clientId`. Because of this, how to correctly assign historical trades and order events is still being determined)
- Manually canceling trigger orders works, however manually modifying doesn't (the trigger ID may be changing, this hasn't been determined yet)

**Comment by cjdsellers** [comment]
Looking forward, we'll incrementally continue to:
- Try and implement full reconciliation
- Use `msgspec` for all HTTP responses and WebSocket messages
- Improve integration of margin features and calculations
- Add more integration tests

**Comment by cjdsellers** [comment]
Due to recent developments, work on the FTX integration has been discontinued.
